# Generated by Django 2.2.7 on 2020-01-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='UserId',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='UserPassword',
            new_name='username',
        ),
    ]
